spring:
  profiles:
    active: dev
  jackson:
    #返回date日期格式化
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    #时区
    time-zone: GMT+8
server:
  tomcat:
    uri-encoding: UTF-8
nomService:
  fileUrl: http://182.92.220.213:8080/file/
  serviceUrl:  http://182.92.220.213:8080/mon/
  softUrl: clientUpdate/newUpdate
update:
  pathName: json

